version: '3.8'

services:
  app:
    build: .
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://postgres:5432/university_ms_db}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME:-postgres}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:-password}
    ports:
      - '8080:8080'
    restart: on-failure
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: university_ms_db
      POSTGRES_USER: ${DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres-data:
